version: "3.9"

services:
  pedido:
    container_name: pedido
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - mysql-network
    entrypoint: ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000", "-jar", "app.jar"]

  mysqldb:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pedido_database
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8081:8080"
    volumes:
      - ./docs/swagger:/usr/share/nginx/html/docs

volumes:
  mysql-data:
  swagger-docs:

networks:
  mysql-network:
    name: mysql-network
