apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA== # root
  mysql-database: ZGJ0ZWNoY2hhbGxhbmdl # dbtechchallange
  mysql-user: dHVybWFmaWFw # turmafiap
  mysql-password: VGVjaEBDaGFsbGFuZ2Uj # Tech@Challange#
  jdbc-datasource-url: amRiYzpteXNxbDovL215c3FsLXNlcnZpY2U6MzMwNi9kYnRlY2hjaGFsbGFuZ2U= # jdbc:mysql://mysql-service:3306/dbtechchallange
